config/routes.rb
Soapclient::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users
  root 'home#index'

  resources :countries, only: :index
  resources :visited_countries, except: :show
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    can :access, :rails_admin if user.admin?

    can :read, Country

    can :read, VisitedCountry
    can :create, VisitedCountry, :user_id => user.id
    can :manage, VisitedCountry, :user_id => user.id
  end
end

app/models/country.rb
class Country < ActiveRecord::Base

  scope :distinct, -> (field) { select(field).distinct.order(field) }
  scope :non_visited_countries, -> (user_id) {
    country = VisitedCountry.where(user_id: user_id).where('end_date < ?', Date.today)
    money_code_ids = country.map {|c| c.country.money_code}
    where(['money_code NOT IN (?)', money_code_ids]) if money_code_ids.any?
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :visited_countries, dependent: :destroy


  def name
    email[/\A[^@]+/].capitalize
  end

end

app/models/visited_country.rb
class VisitedCountry < ActiveRecord::Base

  belongs_to :country
  belongs_to :user
  validates_uniqueness_of :country_id, :scope => :user_id
  validate :check_visited_date

  def check_visited_date
    vc = VisitedCountry.where(user_id: user_id).where('start_date <= ?', end_date).where('end_date >= ?', start_date)
    vc = vc.where('id <> ?', id) if self.id
    errors.add(:start_date, "At this time you ride into #{vc.first.country.try(:name)}") if vc.first
  end

  def end_date= dt
    self[:end_date] = dt
    self[:end_date] = self[:start_date] if self[:end_date] < self[:start_date]
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash.now[:alert] = exception.message
    redirect_to main_app.root_path
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  # GET /countries
  def index
    non_visited_countries = current_user.nil? ? Country.all : Country.non_visited_countries(current_user.id)
    @countries = filters(non_visited_countries, params)
    @all_user_countries = current_user.visited_countries.map(&:country_id) if current_user
  end

  private
    def filters countries, params
      fields = [:name, :code, :money_name, :money_code, :money_symbol]
      fields.each do |field|
        countries = countries.where(field => params[field]) unless params[field].blank?
      end
      countries.order(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/visited_countries_controller.rb
class VisitedCountriesController < ApplicationController
  before_action :set_visited_country, only: [:edit, :update, :destroy]
  authorize_resource except: [:index]

  # GET /visited_countries
  def index
    if params['user_id']
      @visited_countries = (user = User.find params['user_id']) ? user.visited_countries : []
    else
      authenticate_user!
      set_countries
    end
  end

  # GET /visited_countries/new
  def new
    @visited_country = VisitedCountry.new
  end

  # GET /visited_countries/1/edit
  def edit
    render :new
  end

  # POST /visited_countries
  def create
    @visited_country = current_user.visited_countries.new(visited_country_params)
    respond_to do |format|
      if @visited_country.save
        set_countries
        format.html { }
        format.js { render "index" }
      else
        format.html { }
        format.js { render action: "new" }
      end
    end
  end

  # PATCH/PUT /visited_countries/1
  def update
    respond_to do |format|
      if @visited_country.update(visited_country_params)
        set_countries
        format.html { }
        format.js {render "index" }
      else
        format.html { }
        format.js { render action: "new" }
      end
    end
  end

  # DELETE /visited_countries/1
  def destroy
    @visited_country.destroy
    redirect_to visited_countries_url, notice: 'Visited country was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visited_country
      @visited_country = current_user.visited_countries.find(params[:id])
    end

    def visited_country_params
      params.require(:visited_country).permit(:country_id, :start_date, :end_date, :description)
    end

    def set_countries
      @visited_countries = current_user.visited_countries.order(:end_date)
      @non_visited_countries = Country.non_visited_countries current_user.id
      @all_user_countries = current_user.visited_countries.map(&:country_id) if current_user
    end

end

app/helpers/countries_helper.rb
module CountriesHelper
  def filter field
    data = Country.distinct(field).map(&field)
    select_tag(field, options_for_select([""]+data))
  end
end

app/views/countries/_country.html.haml
%tr.data-row
  %td.col-md-4
    - if current_user.nil? || @all_user_countries.include?(country.id)
      = country.name
    - else
      = link_to country.name, new_visited_country_path(country_id: country.id), remote: true
  %td.col-md-1= country.code
  %td.col-md-3= country.money_name
  %td.col-md-2= country.money_code
  %td.col-md-2= country.money_symbol

app/views/countries/index.html.haml
%h1 Listing countries

%table.table
  %tr
    %th Name
    %th Code
    %th Money name
    %th Money code
    %th Money symbol
  %tr#filter
    %td= filter :name
    %td= filter :code
    %td= filter :money_name
    %td= filter :money_code
    %td= filter :money_symbol
  = render @countries

app/views/countries/index.js.haml
:plain
  $('#myModal').modal('hide');
  $('.data-row').remove();
  $("#filter").after("#{ j render @countries }");

app/views/home/index.html.haml
%H2 Collectors
%ul
  - User.all.each do |user|
    %li= link_to user.name, visited_countries_path(user_id: user.id)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Soap client
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  %body
    .spinner{style: 'display: none'}
    .container
      .row-fluid
        .well.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Home', root_path
            %li= link_to 'Countries', countries_path
            - if current_user
              %li= link_to 'Visited countries', visited_countries_path
            - if current_user
              %li= link_to "(#{current_user.name}) Sign out", destroy_user_session_path, :method => :delete
            - else
              %li= link_to 'Sign in', new_user_session_path
        .span10
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              .alert.alert-dismissable{class: "#{name == 'alert' ? 'alert-danger' : 'alert-info'}"}
                %a.close{data: {dismiss: :alert}} &times;
                = msg
          = yield

app/views/visited_countries/_form.html.haml
#myModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title= "Country #{@visited_country.country.try(:name)}"
      .modal-body
        = form_for @visited_country, remote: true do |f|
          - if @visited_country.errors.any?
            .alert.alert-warning
              %h5= "#{pluralize(@visited_country.errors.count, "error")} prohibited this visited_country from being saved:"
              %ul
                - @visited_country.errors.full_messages.each do |msg|
                  %li= msg
          .input-group
            = f.label :description
            = f.text_field :description, placeholder: 'Description', class: 'form-control'
            = f.hidden_field :country_id, value: (params[:country_id] || @visited_country.country.try(:id))
          .input-group
            = f.label :start_date
            = f.text_field :start_date, placeholder: 'Start date', required: '', class: 'form-control cal', value: params[:action] == 'new' ? Date.today.to_s : f.object.start_date
          .input-group
            = f.label :end_date
            = f.text_field :end_date, placeholder: 'End date', required: '', class: 'form-control cal', value: params[:action] == 'new' ? Date.today.to_s : f.object.end_date
          %br/
          .input-group
            = f.submit 'Save', class: 'btn btn-primary form-control'

app/views/visited_countries/_visited_country.html.haml
%tr.data-visited{class: "#{'success' if visited_country.end_date < Date.today}"}
  %td= visited_country.country.name
  %td= visited_country.country.money_name
  %td= visited_country.country.money_code
  %td= visited_country.country.money_symbol
  %td= visited_country.start_date
  %td= visited_country.end_date
  %td= visited_country.description
  - unless params['user_id']
    - if can? :manage, visited_country
      %td= link_to 'Edit', edit_visited_country_path(visited_country, country_id: visited_country.country_id), remote: true
      %td= link_to 'Destroy', visited_country, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/visited_countries/index.html.haml
%h1 Visited countries

%table.table.visited
  %tr#visited
    %th Name
    %th Money name
    %th Money code
    %th Money symbol
    %th Start date
    %th End date
    %th Description
    - unless params['user_id']
      %th
      %th
  = render @visited_countries

%hr/
- unless params['user_id']
  %h2 You can visit these countries to collect the missing currency
  %table.table.all-countries
    %tr#filter
      %th.col-md-4 Name
      %th.col-md-1 Code
      %th.col-md-3.money_filter
        Money name
        = filter :money_name
      %th.col-md-2 Money code
      %th.col-md-2 Money symbol
    = render @non_visited_countries

app/views/visited_countries/index.js.haml
:plain
  $('#myModal').modal('hide');
  $('.ui-datepicker-div').remove();
  $('.modal-backdrop').remove();
  $('#myModal').remove();
  $('body').removeClass('modal-open');
  $('.data-row').remove();
  $("#filter").after("#{ j render @non_visited_countries }");
  $('.data-visited').remove();
  $("#visited").after("#{ j render @visited_countries }");

app/views/visited_countries/new.js.haml
:plain
  $('#myModal').modal('hide');
  $('#myModal').remove();
  $('body').append("#{ j render partial: 'visited_countries/form' }");
  $('#myModal').modal({
    keyboard:true,
    backdrop:true,
    show:true
  });
  $(".cal").datepicker({ dateFormat: "yy-mm-dd" });